### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by sujunglee** [dictyBase/dicty18#10]
Issues with the mobile view:
**Issue 1:** The material-ui navbar is not responsive for mobile views. Even after looking through all of the documentation, it seems like the framework does not provide a straight forward way to address this (which I find rather odd). This causes an issue where the navbar is much longer than the body sections
**Issue 2:** The translucent text box on the header image overflows into the lower sections
**Issue 3:** The agenda table spills out of the body section. The table is too long to be displayed well on a mobile screen, so I need to think of a way to address this

Below is a screenshot of a preview of what it could potentially look like on an iPhone screen (preview provided by Google Chrome dev tools). To sum it up, it looks like a disaster
<img width="333" alt="screen shot 2018-04-18 at 1 51 51 am" src="https://user-images.githubusercontent.com/24560111/38915927-1e24b9ae-42ab-11e8-8ed9-ce619a09443c.png">

**Comment by cybersiddhu** [comment]
Preferably add a screenshot

cc: @pfey03

**Comment by sujunglee** [comment]
[This link](https://www.liquidlight.co.uk/blog/article/tables-in-responsive-design/) has various suggestions on how to style a table to be optimized for a mobile screen. @cybersiddhu @pfey03 @wildlifehexagon any suggestions on which method I should pursue?

**Comment by pfey03** [comment]
@sujunglee I think for the table in Agenda we should use **Horizontal scrolling option 2** from your link above. So fixed on the left are the hours and since the rest is days of the week, horizontal scrolling might be good option. Not complicated and easy to see day by day.

**Comment by pfey03** [comment]
Your top of page GIF above looks good to me too! @sujunglee

**Comment by sujunglee** [comment]
Fixed issue 3 (look at gif below) by adding single-day view that shows up very nicely on a mobile screen. Still need to fix issue 2

![ezgif-4-c8074c83e2](https://user-images.githubusercontent.com/24560111/39109759-e0a3aed6-4693-11e8-8292-fd0915fdb304.gif)

**Comment by pfey03** [comment]
It's also here, didn't see that at first but coffee breaks are chopped short

**Comment by sujunglee** [comment]
Issue 3 fixed: 
![ezgif-4-5bbd50bbd1](https://user-images.githubusercontent.com/24560111/39166429-3276262e-474f-11e8-9996-c7dc79e28ae2.gif)
